version: '3.7'

services:
  db:
    image: mysql:8.4
    command: --mysql-native-password=ON
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: github_covid_modelling_dev
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      # This helps browse the DB from outside the container in development.
      # Comment this out if it's clashing with another MySQL you have running
      # for other purposes.
      - 3306:3306

  web:
    build:
      context: .
      target: dev
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - docker_next:/app/.next
      - node_modules:/app/node_modules
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: github_covid_modelling_dev

  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - docker_next:/app/.next
      - node_modules:/app/node_modules

  release:
    build:
      context: .
      target: release
    # This is set this way to make things easier in the Actions workflows.
    image: image

volumes:
  docker_next:
  node_modules:
  mysql_data:
