#! /bin/bash

#curl 'https://covid-modelling-stg.epcc.ed.ac.uk/api/simulations' \
#  -H "Authorization: token $PAT" \
#  -H 'Content-Type: text/plain;charset=UTF-8' \
#  --data @test-job-api.json

#curl -v -L -X POST \
#  https://api.github.com/repos/covid-policy-modelling/control-plane-dev/dispatches  \
#  -H "Accept: application/vnd.github.everest-preview+json" \
#  -H "Authorization: token $PAT" \
#  --data @test-job-control-plane.json
